-- 코드를 입력하세요

# SELECT FLAVOR, SUM(TOTAL_ORDER) FROM JULY
# GROUP BY FLAVOR

# SELECT FLAVOR, SUM(TOTAL_ORDER) FROM FIRST_HALF
# GROUP BY FLAVOR

SELECT FLAVOR FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS ONE FROM JULY GROUP BY FLAVOR) AS FIRST
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TWO FROM FIRST_HALF GROUP BY FLAVOR) AS SECOND 
USING (FLAVOR)
ORDER BY (ONE+TWO) DESC LIMIT 0,3 
